name: Container Build

on:
  push:
    branches:
      - main

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | podman login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push
        run: |
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
          podman build -f Containerfile -t ghcr.io/${{ github.repository }}:latest -t ghcr.io/${{ github.repository }}:${SHORT_SHA} .
          podman push ghcr.io/${{ github.repository }}:latest
          podman push ghcr.io/${{ github.repository }}:${SHORT_SHA}
